### ISSUE TITLE
Apparently the thing only works on Win 8.1 or higher? That's what I got when I tried to open it with my Win 7.

### ISSUE THREAD

**Issue by Anatoli1** [Fiddlekins/akun-story-scraper#5]

**Comment by Fiddlekins** [comment]
Sorry about that, I forgot that the latest version of node.js no longer supports windows 7
I've added a separate version that uses a version of node.js that will run fine on win7 here: https://github.com/Fiddlekins/akun-story-scraper/releases/tag/1.6.0

**Comment by Anatoli1** [comment]
Thank you. 

Annoying that Win 7 is no longer supported by some programs. It certainly doesn't feel inferior to any latter windows versions.
